sudo: false
language: java
jdk:
- openjdk11
install: "./gradlew assemble"

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
  - gradle externalCiTest

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_4f1b6fd74eac_key -iv $encrypted_4f1b6fd74eac_iv
  -in gradle.properties.enc -out gradle.properties -d
group: "stable"
os: "linux"